# Generated by Django 3.2.9 on 2021-11-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Product Name:')),
                ('description', models.TextField(max_length=300, verbose_name='Product Description:')),
                ('image', models.ImageField(upload_to='static/', verbose_name='Product Image:')),
                ('category', models.CharField(choices=[('1', '')], max_length=100, verbose_name='Product Category:')),
                ('price', models.CharField(max_length=80, verbose_name='Product Price:')),
                ('quantity', models.IntegerField(verbose_name='Product Quantity:')),
            ],
        ),
    ]
