# Generated by Django 3.2.9 on 2021-11-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addProd',
            new_name='Product',
        ),
    ]
