# Generated by Django 3.2.9 on 2021-11-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20211122_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='Is Agent'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_product_manager',
            field=models.BooleanField(default=False, verbose_name='Is Product Manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_simple_user',
            field=models.BooleanField(default=True, verbose_name='Is Simple User'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_stock_manager',
            field=models.BooleanField(default=False, verbose_name='Is Stock Manager'),
        ),
    ]
