# Generated by Django 3.2.9 on 2021-11-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20211122_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined',
            field=models.DateTimeField(auto_now=True, verbose_name='Joined date:'),
        ),
    ]
