# Generated by Django 3.2.9 on 2021-11-24 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_user_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined',
        ),
    ]
